server:
  port: 8000

eureka:
  instance:
    hostname: 47.103.52.41
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

